### ISSUE TITLE
importFileExports grouped option can create invalid import names

### ISSUE THREAD

**Issue by forivall** [life777/test-file-maker#6]
With the option 
```json
	"testFileMaker.importFileExports": "grouped"
```

when the file name includes a hypen, like "file-name.ts", this will create an import like

```ts
import file-name from '../src/file-name';
```

which is invalid code.

**Comment by life777** [comment]
This issue is fixed here: [fixed default grouped variable name. #8](https://github.com/life777/test-file-maker/pull/8)
